# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tGames' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tGames
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'UIScrollView-InfiniteScroll'

  target 'tGamesTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'Quick'
    pod 'Nimble'
  end

  target 'tGamesUITests' do
    inherit! :search_paths
    # Pods for testing

    pod 'Quick'
    pod 'Nimble'
  end

end
